# Generated by Django 5.1.5 on 2025-02-23 09:55

from django.db import migrations

def create_creator_role(apps, schema_editor):
    Role = apps.get_model("organization", "Role")

    Role.objects.create(
        name="Creator",
        level=100,
        permissions= ["create_an_organization"]
    )

class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_creator_role),
    ]
