# Generated by Django 5.1.5 on 2025-02-09 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_branch_branch_admins_department_department_heads_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='branch_admins',
            new_name='admins',
        ),
        migrations.RenameField(
            model_name='designation',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='historicaldesignation',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='employees',
        ),
        migrations.AddField(
            model_name='branch',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='branch',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalbranch',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalbranch',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalbranch',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalbranch',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='historicalbranch',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='headquarters',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The main headquarters of the organization.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='historicalorganization',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='headquarters',
            field=models.OneToOneField(blank=True, help_text='The main headquarters of the organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hq_of', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalbranch',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='superusers',
            field=models.ManyToManyField(blank=True, related_name='superuser_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='designation',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_designation_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='unique_location_per_organization'),
        ),
    ]
