# Generated by Django 5.1.5 on 2025-02-09 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_rename_branch_admins_branch_admins_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='superusers',
            field=models.ManyToManyField(blank=True, null=True, related_name='superuser_organizations', to=settings.AUTH_USER_MODEL),
        ),
    ]
