# Generated by Django 5.1.5 on 2025-02-23 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingotp',
            name='organization',
        ),
    ]
