# Generated by Django 5.1.5 on 2025-02-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='organization',
        ),
        migrations.AddField(
            model_name='customuser',
            name='actvie_status',
            field=models.BooleanField(default=False),
        ),
    ]
