# Generated by Django 5.1.5 on 2025-02-09 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_customuser_archived_customuser_archived_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='actvie_status',
            new_name='active_status',
        ),
        migrations.RenameField(
            model_name='historicalcustomuser',
            old_name='actvie_status',
            new_name='active_status',
        ),
    ]
