# Generated by Django 5.1.5 on 2025-02-06 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('organization', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leavepermission',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavepermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavepolicy',
            name='designation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_policy', to='organization.designation'),
        ),
        migrations.AddField(
            model_name='logindetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logindetails',
            name='workitems',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_sessions', to='tasks.workitem'),
        ),
    ]
